### ISSUE TITLE
求配置openwrt教程  另外我发现学校疑似没有配置对于路由的检测

### ISSUE THREAD

**Issue by kkidnb** [YaYa404/ZJKJU-Network-Login#1]
是将脚本参数补充完成之后，在openwrt配置好python环境，设置执行指令就可以了吗？
将openwrt路由连接到校园网后，用任意设备连接之后就提示认证，认证过后连上路由的设备都能联网了。想问下学长zjkju的校园网是不是没有设置相关的检测机制？

**Comment by YaYa404** [comment]
我们学校初期因为网络不稳定老是掉线就写了这个脚本，现在无感认证稳定了其实就不用这个了，直接在连接路由器的设备上登录开启无感认证，他的mac对应的就是路由器。

其次是我们的校园网是有检测的，可以明确告诉你有UA检测，其他的不知道，我的方法是境外流量走openclash，境内流量走ua3f（因为我路由器性能比较好你也可以用ua2f），然后TTL设置64在路由器，NTP时钟统一在路由器授时。

如果你还要用这脚本的话，这脚本我检测写得不是很好，应该加上一条如果网络还联通就不用登录（我当前只判断了登录页面是否需要登录），可以改一下。
理论上配置完运行就可以了，但是我建议直接用docker部署，简单省事。

**Comment by kkidnb** [comment]
好的，之前不知为何能运作起来，没有提示代理用了两天，今天提示检测到代理行为了🥹
我尝试下跑ua3f吧，另外想问下用校园网走境外学校不管吗
我试试能不能在docker部署吧 还是有点不太熟悉docker，如果不行我再向你请教 谢谢学长

**Comment by YaYa404** [comment]
境外流量都是加密的https，他想管也管不了啊，他顶多也只能看到跳板的ip

**Comment by kkidnb** [comment]
好的 感谢学长
我已经部署好ua3f 防检测是部署成功了
在opwrt用你提供的dockerfile构建好了镜像
我容器的配置 "镜像选择zjkju-login，重启策略选择unless stopped，其他都保持默认"
这样可以正常运行吗  （不会python，脚本等大佬更新）
![IMG_20241210_171447](https://github.com/user-attachments/assets/37a4bafb-e0db-4cca-a908-1cebf703c0a7)

![屏幕截图 2024-12-10 170512](https://github.com/user-attachments/assets/98cca38f-1662-4b25-bea0-a10463e707ca)

**Comment by kkidnb** [comment]
我手动下线 发现是可以自动登录的，期待更新改进版脚本。
issues我就关闭了，再次感谢
